// Generated by build script, do not edit!
#ifndef RC_INVOKED

#include "Configuration/IntegerDefinitions.h"
#include "Runtime/Testing/Fakeable.h"

namespace UnityConfig
{
    extern const char* const UnityCompany = "Unity Technologies";
    extern const char* const UnityCopyright = "(c) 2005-2023 Unity Technologies. All rights reserved.";
    extern const bool HardwareStatsEnabled = 1;
    extern const char* const BuildRoot = "C:/jenkins/sharedspace/ra_2022.3";

    extern const char* const UnityVersion = "2022.3.2f1c1";
    extern const char* const UnityVersionDigits = "2022.3.2";
    extern const char* const UnityVersionSuffix = "f1c1";
    extern const UInt32 UnityVersionVer = 2022;
    extern const UInt32 UnityVersionMajor = 3;
    extern const UInt32 UnityVersionMinor = 2;
    extern const bool UnityVersionIsBeta = 0;

    extern const char* const UnityVersionUnderHash = "2022.3.2f1c1_891eba2b6e38";
    extern const char* const UnityVersionUnderHash_Verbose = "2022.3.2f1c1.git.or.8986298_891eba2b6e38";
    extern const char* const UnityVersionUnderHash_WithParens = "2022.3.2f1c1 (891eba2b6e38)";

    // A numeric representation of the version control hash
    extern const UInt64 UnityVersionBuild = 8986298;

    extern const UInt64 UnityVersionDate = 1688549060;
    extern const char* const UnityVersionBranch = "origin/2022.3/china_unity/release";
    extern const char* const UnityVersionDisplay = "2022.3.2f1c1.git.origin/2022.3/china_unity/release.8986298";
    extern const char* const UnityVersionDisplay_Verbose = "2022.3.2f1c1.git.origin/2022.3/china_unity/release.8986298";
    extern const char* const UnityVersionRevision = "891eba2b6e38";

    // Wide strings
    extern const wchar_t* const L_UnityVersionUnderHash_WithParens = L"2022.3.2f1c1 (891eba2b6e38)";
    extern const wchar_t* const L_UnityVersion = L"2022.3.2f1c1";
}

#else // Generated by build script for sole use by the Windows resource compiler, do not use for anything else

    #define UNITY_COMPANY "Unity Technologies"
    #define UNITY_COPYRIGHT "(c) 2005-2023 Unity Technologies. All rights reserved."
    #define UNITY_VERSION_VER 2022
    #define UNITY_VERSION_MAJ 3
    #define UNITY_VERSION_MIN 2
    #define UNITY_IS_BETA 0
    #define UNITY_VERSION_UNDER_HASH "2022.3.2f1c1_891eba2b6e38"
    #define UNITY_VERSION_PARENS_HASH "2022.3.2f1c1 (891eba2b6e38)"
    #define UNITY_VERSION_BLD 8986298
    #define UNITY_VERSION_WIN "2022.3.2.8986298"

#endif // !RC_INVOKED
